Repository getferdi/ferdi, pull requests merged in 2021-07, with the labels that each got.

#1606 Removed references to png images
  src/api/server/ServerApi.js
  src/i18n/locales/defaultMessages.json
  src/i18n/messages/src/lib/Menu.json
  src/models/Service.js
Labels: tech-debt/cleanup

#1609 Added new help text for lay-users to figure out what their user-agent value is
  src/components/settings/services/EditServiceForm.js
  src/components/settings/settings/EditSettingsForm.js
  src/i18n/globalMessages.js
  src/i18n/locales/defaultMessages.json
  src/i18n/locales/en-US.json
  src/i18n/messages/src/components/settings/services/EditServiceForm.json
  src/i18n/messages/src/components/settings/settings/EditSettingsForm.json
  src/i18n/messages/src/i18n/globalMessages.json
  src/styles/settings.scss
Labels: documentation

#1610 Separated version number bump into the 'develop' branch from 'nightly' branch
  .github/workflows/dependency-updates.yml
  .github/workflows/ferdi-builds.yml
Labels: devops, high priority, tech-debt/cleanup

#1611 Building ferdi on an ARM machine
  .dockerignore
  CONTRIBUTING.md
  Dockerfile
Labels: devops

#1582 Enabled signing of windows build artifacts on 'nightly' and 'release' branches
  .github/workflows/ferdi-builds.yml
Labels: devops, high priority

#1486 Fix hibernation mode
  src/components/layout/Sidebar.js
  src/components/services/content/ServiceView.js
  src/components/services/tabs/TabBarSortableList.js
  src/components/services/tabs/TabItem.js
  src/components/services/tabs/Tabbar.js
  src/components/settings/services/EditServiceForm.js
  src/components/settings/settings/EditSettingsForm.js
  src/containers/layout/AppLayoutContainer.js
  src/containers/settings/EditServiceScreen.js
  src/containers/settings/EditSettingsScreen.js
  src/environment.js
  src/i18n/locales/defaultMessages.json
  src/i18n/locales/en-US.json
  src/i18n/messages/src/components/services/tabs/TabItem.json
  src/i18n/messages/src/containers/settings/EditSettingsScreen.json
  src/i18n/messages/src/features/workspaces/components/WorkspaceDrawer.json
  src/models/Service.js
  src/stores/ServicesStore.js
Labels: high priority, security

#1680 Added a 'wakeUpStrategy' that the user can control to wake up a previ…
  src/components/settings/settings/EditSettingsForm.js
  src/config.js
  src/containers/settings/EditSettingsScreen.js
  src/environment.js
  src/i18n/locales/defaultMessages.json
  src/i18n/locales/en-US.json
  src/i18n/messages/src/containers/settings/EditSettingsScreen.json
  src/models/Service.js
  src/stores/ServicesStore.js
Labels: enhancement, high priority
