Repository getferdi/ferdi, pull requests merged in 2021-08, with the labels that each got.

#1750 Removed nested 'package-lock' files; Some other cleanups (break-off from #1714)
  package-lock.json
  package.json
  packages/forms/package-lock.json
  packages/forms/package.json
  packages/theme/package-lock.json
  packages/ui/package-lock.json
  packages/ui/src/index.ts
Labels: tech-debt/cleanup

#1752 Path-references refactoring and using 'import' instead of 'require'
  src/api/server/ServerApi.js
  src/components/services/content/ServiceWebview.js
  src/components/services/tabs/TabBarSortableList.js
  src/containers/settings/RecipesScreen.js
  src/electron/Settings.js
  src/electron/ipc-api/appIndicator.js
  src/electron/ipc-api/download.js
  src/electron/ipc-api/localServer.js
  src/electron/macOSPermissions.js
  src/electron/webview-ime-focus.js
  src/environment.js
  src/helpers/recipe-helpers.js
  src/helpers/service-helpers.js
  src/helpers/userAgent-helpers.js
  src/index.js
  src/internal-server/start.js
  src/lib/Tray.js
  src/models/Recipe.js
  src/models/Service.js
  src/scripts/add-crowdin-contributors.js
  src/scripts/build-theme-info.js
  src/scripts/link-readme.js
  src/stores/AppStore.js
  src/stores/RecipesStore.js
  src/stores/ServicesStore.js
  src/webview/darkmode.js
  src/webview/lib/RecipeWebview.js
  src/webview/recipe.js
Labels: tech-debt/cleanup

#1760 Add new Help menu item to allow easy import/export of config data
  CHANGELOG.md
  src/components/services/content/Services.js
  src/config.js
  src/electron/ipc-api/localServer.js
  src/i18n/locales/af.json
  src/i18n/locales/be.json
  src/i18n/locales/bs.json
  src/i18n/locales/ca.json
  src/i18n/locales/cs.json
  src/i18n/locales/defaultMessages.json
  src/i18n/locales/el.json
  src/i18n/locales/en-US.json
  src/i18n/locales/ga.json
  src/i18n/locales/he.json
  src/i18n/locales/hr.json
  src/i18n/locales/hu.json
  src/i18n/locales/id.json
  src/i18n/locales/ka.json
  src/i18n/locales/ko.json
  src/i18n/locales/nl-BE.json
  src/i18n/locales/nl.json
  src/i18n/locales/pl.json
  src/i18n/locales/ro.json
  src/i18n/locales/ru.json
  src/i18n/locales/sk.json
  src/i18n/locales/sl.json
  src/i18n/locales/sr.json
  src/i18n/locales/tr.json
  src/i18n/locales/uk.json
  src/i18n/locales/vi.json
  src/i18n/locales/zh-CN.json
  src/i18n/locales/zh-HANT.json
  src/i18n/locales/zh.json
  src/i18n/messages/src/components/services/content/Services.json
  src/i18n/messages/src/lib/Menu.json
  src/internal-server/env.ini
  src/lib/Menu.js
Labels: enhancement

#1767 build: add Ferdi snap package
  .github/workflows/ferdi-builds.yml
  electron-builder.yml
Labels: enhancement, high priority

#1757 feat: follow OS reduced motion setting
  .eslintrc
  packages/forms/src/button/index.tsx
  packages/forms/src/select/index.tsx
  packages/forms/src/toggle/index.tsx
  packages/ui/src/infobox/index.tsx
  src/components/auth/SetupAssistant.js
  src/components/layout/AppLayout.js
  src/components/services/content/ConnectionLostBanner.js
  src/components/services/tabs/TabItem.js
  src/components/ui/AppLoader/styles.js
  src/features/webControls/components/WebControls.js
  src/features/workspaces/components/WorkspaceDrawerItem.js
  src/features/workspaces/components/WorkspaceSwitchingIndicator.js
  src/i18n/locales/defaultMessages.json
  src/i18n/messages/src/components/auth/SetupAssistant.json
  src/i18n/messages/src/components/layout/AppLayout.json
  src/i18n/messages/src/components/services/content/ConnectionLostBanner.json
  src/i18n/messages/src/components/services/tabs/TabItem.json
  src/i18n/messages/src/features/webControls/components/WebControls.json
  src/index.html
  src/internal-server/public/css/main.css
  src/styles/button.scss
  src/styles/content-tabs.scss
  src/styles/fonts.scss
  src/styles/image-upload.scss
  src/styles/layout.scss
  src/styles/main.scss
  src/styles/radio.scss
  src/styles/recipes.scss
  src/styles/settings.scss
  src/styles/slider.scss
  src/styles/tabs.scss
  src/styles/toggle.scss
  src/styles/type.scss
  src/styles/welcome.scss
  src/webview/screenshare.js
Labels: enhancement

#1776 Fix error while importing without workspaces
  CHANGELOG.md
  src/internal-server/app/Controllers/Http/UserController.js
Labels: bug, high priority

#1785 Quick access to Ferdi Profile folder
  src/components/settings/settings/EditSettingsForm.js
  src/containers/settings/RecipesScreen.js
  src/environment.js
  src/i18n/locales/defaultMessages.json
  src/i18n/locales/en-US.json
  src/i18n/messages/src/components/settings/settings/EditSettingsForm.json
  src/index.js
  src/styles/settings.scss
Labels: enhancement

#1789 Refactoring: Url helpers
  src/components/settings/settings/EditSettingsForm.js
  src/components/ui/Link.js
  src/containers/settings/RecipesScreen.js
  src/environment.js
  src/helpers/url-helpers.js
  src/i18n/messages/src/components/settings/settings/EditSettingsForm.json
  src/i18n/messages/src/lib/Menu.json
  src/index.js
  src/lib/Menu.js
  src/stores/AppStore.js
  src/webview/contextMenuBuilder.js
Labels: tech-debt/cleanup

#1790 Initial plumbing and conversion of a simple javascript to typescript
  .gitignore
  gulpfile.babel.js
  package-lock.json
  package.json
  src/helpers/url-helpers.ts
  tsconfig.json
  tsconfig.settings.json
Labels: tech-debt/cleanup

#1793 Fix issue with shortcut accelerators not working on macos where symbols were used for shift/alt keys
  src/components/services/tabs/TabItem.js
  src/environment.js
  src/features/workspaces/components/WorkspaceDrawerItem.js
  src/lib/Menu.js
  src/webview/contextMenuBuilder.js
Labels: bug, high priority

#1798 Minor cleanup of gulp
  gulpfile.babel.js
Labels: tech-debt/cleanup

#1801 Fix issue with left-clicking regression
  src/helpers/url-helpers.ts
Labels: bug, high priority

#1804 chore: replace moment.js with day.js
  package-lock.json
  package.json
  src/stores/AppStore.js
  src/stores/UserStore.js
Labels: tech-debt/cleanup

#1805 Typescript conversion
  src/models/News.ts
  src/models/Order.js
  src/models/Order.ts
  src/models/Recipe.ts
  src/models/RecipePreview.ts
  src/models/User.ts
Labels: tech-debt/cleanup

#1823 Decouple audio toggle from Notification toggle
  src/stores/ServicesStore.js
Labels: bug

#1834 Fix reordering of services in vertical style layout
  CHANGELOG.md
  src/components/layout/Sidebar.js
  src/components/services/tabs/Tabbar.js
Labels: appearance
