Repository getferdi/ferdi, pull requests merged in 2021-10, with the labels that each got.

#2005 Reduce dependency on 'electron-utils' and 'electron-is-dev'
  src/environment.ts
Labels: tech-debt/cleanup

#2007 feat: show service number on icon when first key of switch service hotkey held
  src/components/services/tabs/TabItem.js
  src/styles/tabs.scss
Labels: hacktoberfest

#2008 refactor: remove 'electron-util' and 'electron-is-dev' as dependencies
  package-lock.json
  package.json
  src/electron-util.ts
  src/enforce-macos-app-location.ts
  src/environment-remote.ts
  src/index.js
Labels: hacktoberfest, high priority, tech-debt/cleanup

#2012 Fix navigation shortcut accelerator (fixes #1172)
  src/lib/Menu.js
Labels: bug, hacktoberfest, high priority

#2002 feat: add a globalShortcut to toggle main window
  src/index.js
Labels: hacktoberfest

#2014 Upgrade 'pnpm' to '6.16.0'
  .github/workflows/dependency-updates.yml
  .github/workflows/ferdi-builds.yml
  CONTRIBUTING.md
  Dockerfile
Labels: hacktoberfest, tech-debt/cleanup

#1860 chore: upgraded electron to 14.1.0
  README.md
  package-lock.json
  package.json
  src/components/auth/AuthLayout.js
  src/components/layout/AppLayout.js
  src/components/services/content/ServiceWebview.js
  src/index.js
Labels: hacktoberfest, tech-debt/cleanup

#2018 Upgrade 'electron' to '15.0.0'
  README.md
  package-lock.json
  package.json
  src/lib/Menu.js
Labels: hacktoberfest, high priority, tech-debt/cleanup

#2019 Updated pl.json
  src/i18n/locales/pl.json
Labels: hacktoberfest, documentation

#2020 Upgrade 'electron' to '15.1.1'
  README.md
  package-lock.json
  package.json
Labels: hacktoberfest, tech-debt/cleanup

#2148 shortcuts for toggling service
  src/components/services/tabs/TabItem.js
Labels: enhancement, hacktoberfest
